### ISSUE TITLE
In test GLM runs, lakes are losing water

### ISSUE THREAD

**Issue by hcorson-dosch-usgs** [DOI-USGS/lake-temperature-process-models#15]
We are currently running the GLM models for each of the 3 time periods for a set of [5 test lakes](https://github.com/USGS-R/lake-temperature-model-prep/issues/254). As of right now, the driver data we are using to run those models is incorrect for 2 reasons: 1) the [feather files](https://doimspp.sharepoint.com/:u:/r/sites/IIDDStaff/Shared%20Documents/Project%20-%20Modeling%20Lakes/GLM/lake-temperature-process-models/ProcessModel_1PrepTmp_files_20211222.zip?csf=1&web=1&e=sVpxxz) that Lindsay is [manually creating](https://github.com/USGS-R/lake-temperature-model-prep/pull/266/files#diff-62dd5893d9413fd0a08f0efcc6670ab6b0aeebcc37db4ec070ba1c1539267c51R174-R198) are still for the [randomly selected subset of 5 lakes](https://github.com/lindsayplatt/lake-temperature-model-prep/blob/gcm_driver_data_munge_pipeline/7_drivers_munge/src/GCM_driver_utils.R#L87-L92) rather than for the 5 test lakes that are GLM-modelable (I am [renaming the feather files](https://doimspp.sharepoint.com/:u:/r/sites/IIDDStaff/Shared%20Documents/Project%20-%20Modeling%20Lakes/GLM/lake-temperature-process-models/ProcessModel_1PrepTmp_files_20211222_HayleyMod.zip?csf=1&web=1&e=bqXuXN) before running the GLM pipeline), and 2) because the GCM data available at the moment through GDP is not the unbiased data.

As a result, I have primarily been focusing only on whether GLM is [successfully running](https://github.com/USGS-R/lake-temperature-process-models/blob/main/2_run/src/run_glm3.R#L137-L171), and not worrying too much about how the output looks. However, the current output (I'm running GLM locally, and using version `3.1.0a4`) shows that the lakes are losing water, despite the nml parameter `disable_evap` being [set to `TRUE`](https://github.com/USGS-R/lake-temperature-process-models/blob/main/1_prep/src/munge_nmls.R#L40-L41). For example, the plotted lake temperatures for 1980-2000 for one lake look like so:
![image](https://user-images.githubusercontent.com/54007288/148270669-f50d9bef-5fe6-42c9-a32a-2aed087e1371.png)

The nml for that run is:
```
&glm_setup
   sim_name = 'nhdhr_{88374465-DA2B-47F8-BFC6-002E7DF1353E}_ACCESS_1980_1999'
   max_layers = 65
   min_layer_vol = 0.5
   min_layer_thick = 0.2
   max_layer_thick = 1
   density_model = 1
   non_avg = .true.
/
&mixing
   surface_mixing = 1
   coef_mix_conv = 0.125
   coef_wind_stir = 0.23
   coef_mix_shear = 0.2
   coef_mix_turb = 0.51
   coef_mix_KH = 0.3
   deep_mixing = 2
   coef_mix_hyp = 0.5
   diff = 0
/
&morphometry
   lake_name = 'nhdhr_{88374465-DA2B-47F8-BFC6-002E7DF1353E}'
   latitude = 45.9322
   longitude = -89.20818
   bsn_len = 1722.875
   bsn_wid = 1722.875
   bsn_vals = 16
   H = 310.856, 311.4656, 312.0752, 312.6848, 313.2944, 313.904, 314.5136, 315.1232, 315.7328, 316.3424, 316.952, 317.5616, 318.1712, 318.7808, 319.3904, 320
   A = 44188.5, 113504, 159714, 252134, 487569, 686067, 1054300, 1261410, 1399480, 1560580, 1606590, 1675650, 1721660, 1951810, 2389040, 2555900
/
&time
   timefmt = 2
   start = '1979-03-09'
   stop = '2000-07-07'
   dt = 3600
   timezone = -6
   num_days = 150
/
&output
   out_dir = 'out'
   out_fn = 'output'
   nsave = 24
   csv_lake_fname = 'lake'
   csv_point_nlevs = 0
   csv_point_fname = 'WQ_'
   csv_point_at = 17
   csv_point_nvars = 2
   csv_point_vars = 'temp','salt','OXY_oxy'
   csv_outlet_allinone = .false.
   csv_outlet_fname = 'outlet_'
   csv_outlet_nvars = 2
   csv_outlet_vars = 'flow','temp','salt','OXY_oxy'
   csv_ovrflw_fname = 'overflow'
/
&init_profiles
   lake_depth = 9.144
   num_depths = 2
   the_depths = 0, 9.14
   the_temps = 3, 4
   the_sals = 0, 0
   num_wq_vars = 0
   wq_names = 'OGM_don','OGM_pon','OGM_dop','OGM_pop','OGM_doc','OGM_poc'
   wq_init_vals = 1.1, 1.2, 2.2, 1.3, 3.3, 4.1, 1.1, 1.2, 2.2, 1.3, 3.3, 4.1
/
&meteorology
   met_sw = .true.
   lw_type = 'LW_IN'
   rain_sw = .false.
   atm_stab = 0
   catchrain = .false.
   rad_mode = 1
   albedo_mode = 1
   cloud_mode = 4
   fetch_mode = 0
   subdaily = .false.
   meteo_fl = 'meteo_fl.csv'
   wind_factor = 1
   sw_factor = 1
   lw_factor = 1
   at_factor = 1
   rh_factor = 1
   rain_factor = 1
   ce = 0.0013
   ch = 0.0013
   cd = 0.001116033
   rain_threshold = 0.01
   runoff_coef = 0.3
/
&bird_model
   AP = 973
   Oz = 0.279
   WatVap = 1.1
   AOD500 = 0.033
   AOD380 = 0.038
   Albedo = 0.2
/
&light
   light_mode = 0
   n_bands = 4
   light_extc = 1, 0.5, 2, 4
   energy_frac = 0.51, 0.45, 0.035, 0.005
   Benthic_Imin = 10
   Kw = 0.9197703
/
&inflow
   num_inflows = 0
   names_of_strms = 'Riv1','Riv2'
   strm_hf_angle = 65, 65
   strmbd_slope = 2, 2
   strmbd_drag = 0.016, 0.016
   inflow_factor = 1, 1
   inflow_fl = 'bcs/inflow_1.csv','bcs/inflow_2.csv'
   inflow_varnum = 2
   inflow_vars = 'FLOW','TEMP'
   time_fmt = 'YYYY-MM-DD'
/
&outflow
   num_outlet = 0
   outflow_fl = 'in/outflow.csv'
   outflow_factor = 0.8
   outflow_thick_limit = 100
   flt_off_sw = .false.
   outlet_type = 1
   outl_elvs = 1
   bsn_len_outl = 5
   bsn_wid_outl = 5
/
&snowice
   dt_iceon_avg = 0.01
   min_ice_thickness = 0.01
   snow_albedo_factor = 0.72
/
&debugging
   disable_evap = .true.
/
```

The nml template is edited [here](https://github.com/USGS-R/lake-temperature-process-models/blob/main/1_prep/src/munge_nmls.R), and finalized [here](https://github.com/USGS-R/lake-temperature-process-models/blob/main/2_run/src/run_glm3.R#L111-L118)

@jread-usgs I wanted to bring this to your attention in case this is a red flag, and does _not_ seem like something that would be resolved when we use the correct, unbiased GCM driver data for each lake.

**Comment by jordansread** [comment]
Yes, this is a bit of a flag because that looks like the kind of thing we'd see when evap > precip over time. And with evap being locked at zero, I'd expect the lake level to stay put. 

It looks like the model is ignoring the `disable_evap` arg, or perhaps in the written nml file it for some reason is missing (perhaps the whole block starting with `&debugging`) but that seems unlikely. Easier to check for the second of these by putting a breakpoint in the function and looking at the written .nml text file right before model execution.

**Comment by hcorson-dosch-usgs** [comment]
That nml file content I inserted above is from the nml file written to the simulation directory (I commented out [the line that deletes those directories](https://github.com/USGS-R/lake-temperature-process-models/blob/main/2_run/src/run_glm3.R#L94) for the moment), so I don't think that is the issue. I had taken a look at the driver data to see if there was anything obviously wrong previously, but will do so again now.

**Comment by hcorson-dosch-usgs** [comment]
Okay took a look again at the biased GCM meteo data, and while there aren't any obviously weird trends in the data, I think we do have some units issues. Here's how the unbiased GCM data compares to NLDAS data used for the DRB reservoir modeling:

| GLM driver input | [Units needed by GLM](https://gmd.copernicus.org/preprints/gmd-2017-257/gmd-2017-257-manuscript-version3.pdf) - see table at p59 | NLDAS_time[0.367700]_x[397]_y[136] range of values (1979-2020) | biased GCM range of values (1980-2000) | 
| ----------- | ----------- | ----------- | ----------- |
| Shortwave      | W/m2  | 16 - 326  | 17 - 330 |
| Longwave   | W/m2 | 140 - 429 | 17 - 330 |
| AirTemp | degC | -24 - 29 | -23 - 38 |
| RelHum | "user supplied relative humidity between 0 and 1", but we have it in percent in the NLDAS data? | 27 - 97 | 0.0004 - 0.018 |
| WindSpeed | m/s | 0.9 - 15 | 1 - 10 |
| Rain | m/day | 0 - 0.1 | 0 - 0.001  |
| Snow | m/day | 0 - 0.7 | 0 - 0.004 |

From quickly plotting the driver data for the run I've plotted the results for, above, the range of the biased GCM Shortwave, Longwave, AirTemp, and WindSpeed look fine (other than the fact that Longwave is identical to Shortwave at the moment, which is a known issue). But the range of the biased RelHum is definitely not equivalent to RelHum in units of percent:
![image](https://user-images.githubusercontent.com/54007288/148285296-cf0a60b5-df0a-4f22-bfef-c0fb71d02985.png)
And the range of rain and snow values are much lower than would be expected in units of m/day:
![image](https://user-images.githubusercontent.com/54007288/148285409-efa8998d-765b-4fd5-805e-853cf79677d3.png)
![image](https://user-images.githubusercontent.com/54007288/148285441-3f23425d-5079-453e-91d6-2bb6ca42340c.png)

What I'm not sure of is whether these values could be throwing off the model enough to explain the dropping water levels, or if we still think something is up with evap.

**Comment by jordansread** [comment]
Good find(s). Perhaps the precip alone explains the decline, but we'll see. 

Scary thought on relative humidity for NLDAS, but I'm convinced the comment on that row is a carryover from the v1 of the model, since all modern examples use RH as 0-100. For example, these files which are available as example simulations from the model developers: https://raw.githubusercontent.com/AquaticEcoDynamics/GLM_Examples/master/EllenBrook/bcs/met_hourly.csv

For the other variables, we know LW is a dummy variable now, so skipping that. The RelHum variable doesn't look to be RH, it looks more like the raw variable from the [thredds host](https://cida.usgs.gov/thredds/dodsC/notaro_ACCESS_1980_1999.html), which is specific humidity. That variable needs to be combined with air temp and pressure to calcuate RH, see [here](https://github.com/USGS-R/lake-temperature-model-prep/blob/main/7_drivers_munge/src/GLM_driver_utils.R#L151). The rain/snow data are in kg m-2 s-1 from THREDDS, so those also need a conversion. 

@lindsayplatt see here for some conversions needed in the GCM munge

**Comment by hcorson-dosch-usgs** [comment]
Woohoo! Converted rain and snow to m/day from kg m-2 s-1, and re-ran the models, and this is now the result for that same model run:
![image](https://user-images.githubusercontent.com/54007288/148296742-b341354c-dce2-4f3b-954e-cdb14a3c6cb7.png)

**Comment by jordansread** [comment]
Nice!!

**Comment by hcorson-dosch-usgs** [comment]
Closing this, as issue is resolved with use of new munged, unbiased GCM data (see [`lake temperature-model-prep` PR #276](https://github.com/USGS-R/lake-temperature-model-prep/pull/276))

Example of output for `nhdhr_122549068` using GCM GFDL in all three time periods:
![image](https://user-images.githubusercontent.com/54007288/150208914-40636f15-ca17-4e0a-92a4-52ec7a4d2d18.png)
![image](https://user-images.githubusercontent.com/54007288/150209054-bd7b0840-050d-4edc-9813-fc59f6741ae2.png)
![image](https://user-images.githubusercontent.com/54007288/150209124-bf164cb5-56f2-4a6a-a2d0-fa3160989bd8.png)

The 1981-2000 projections for the ACCESS GCM in all three lakes( `nhdhr_121545089` `nhdhr_121543975` `nhdhr_122549068`) do show some reduction in depth, but it's much smaller than seen previously in other lakes (e.g., ~0.5m out of 3m vs 4m out of 8+m), as seen in this plot for `nhdhr_122549068`:
![image](https://user-images.githubusercontent.com/54007288/150209333-6fb5ee4d-aecb-4993-8acc-85c9580c3da0.png)

The results for the 1981-2000 period for `nhdhr_122549068` for CNRM, IPSL, MRI, and MIROC5 all look akin to those for GFDL, and do not show that reduction in depth that the ACCESS results, so I don't think there's any cause for concern with the model or data at the moment.
