### ISSUE TITLE
Inspect initial model results

### ISSUE THREAD

**Issue by hcorson-dosch-usgs** [DOI-USGS/lake-temperature-process-models#18]
Alright, in order to start looking at some of the results for the model runs that did succeed, I've pulled down GLM output for 5 lake-gcm combos (15 model runs in all). These results are from the [latest full run using version 3.2.0a8 that finished on 1/26/22](https://github.com/USGS-R/lake-temperature-process-models/issues/2#issuecomment-1022405070):
```r
  tar_target(p2_glm_uncalibrated_runs_csv, '2_run/tmp/p2_glm_uncalibrated_runs_20220126.csv'),
  tar_target(p2_glm_uncalibrated_runs, 
             readr::read_csv(p2_glm_uncalibrated_runs_csv, col_types=cols()) %>%
               filter((lake_id=='nhdhr_45361793' & gcm=='CNRM') |
                        (lake_id=='nhdhr_59724783' & gcm=='IPSL') |
                        (lake_id=='nhdhr_72863673' & gcm=='MRI') |
                        (lake_id=='nhdhr_120018623' & gcm=='GFDL') |
                        (lake_id=='nhdhr_166867643' & gcm=='ACCESS'))
            ),
```
As a start, I put together plots of GLM predictions (by DOY) within each of the three time periods, faceted by depth class (surface, middle, bottom). All GLM preds within each period are plotted in the light blue, and the mean of those predictions within each period is plotted in dark blue:
![image](https://user-images.githubusercontent.com/54007288/152075033-9ba7bbe5-73b5-491a-bb3d-c0242c7802a3.png)
![image](https://user-images.githubusercontent.com/54007288/152075049-71ab2ec4-3906-4989-a048-dfbfe89230c7.png)
![image](https://user-images.githubusercontent.com/54007288/152075100-9dd6677f-4584-463a-8101-bbf041b0c0b2.png)
![image](https://user-images.githubusercontent.com/54007288/152075116-eec6e46d-baa3-454c-93e1-77d1eb47eafd.png)
![image](https://user-images.githubusercontent.com/54007288/152075133-7c27e314-ae7d-4eea-a41a-7ea84c9ca26d.png)

I'll keep plotting tomorrow, and I'm happy to put together specific plots, or pull down more results, depending on what would be useful to investigate.

Any requests @jread-usgs ?

**Comment by jordansread** [comment]
Great! I think the one additional thing that would help is an indicator of ice/no ice. Perhaps just a different plot marker at 0° when there is ice would be a simple way to get that info in there?

**Comment by hcorson-dosch-usgs** [comment]
Okay I've put a series of plots [here](https://doimspp.sharepoint.com/sites/IIDDStaff/Shared%20Documents/Project%20-%20Modeling%20Lakes/GLM/lake-temperature-process-models/Initial_plots_20220204)

For 10 lakes we have plots of surface, middle, and bottom predictions averaged across 20-year periods, across all GCMs:
![20yr_preds_nhdhr_166867643](https://user-images.githubusercontent.com/54007288/152613554-23f1359e-9673-4eb9-bed7-6ca2c52157c2.png)

And broken out individually by GCM:
![20yr_preds_ice_nhdhr_166867643_MIROC5](https://user-images.githubusercontent.com/54007288/152613586-94c2a3e3-a4b1-4061-a0e3-e97feb1b17fe.png)

And then profiles of temperatures on 4 dates, averaged across 20-year periods, across all GCMs.
![20yr_profiles_nhdhr_166867643](https://user-images.githubusercontent.com/54007288/152613609-6226b080-7812-4fb7-beab-2e72a66f58be.png)

**Comment by hcorson-dosch-usgs** [comment]
Plots for the same 10 sites generated with results from the [latest run](https://github.com/USGS-R/lake-temperature-process-models/issues/2#issuecomment-1033243751) are [here](https://doimspp.sharepoint.com/:f:/r/sites/IIDDStaff/Shared%20Documents/Project%20-%20Modeling%20Lakes/GLM/lake-temperature-process-models/Plots_w_updated_grid_20220210?csf=1&web=1&e=XoNnhB)

**Comment by lindsayplatt** [comment]
@hcorson-dosch I think our job here for inspecting initial successful results is complete? Do you want to do the honors of closing??

**Comment by hcorson-dosch-usgs** [comment]
@lindsayplatt I don't think Jordan has reviewed any of this yet, so I'd like to leave it open.

**Comment by lindsayplatt** [comment]
If that's the case, I think he needs to be assigned this issue and tagged so that he knows we are waiting on him. I feel like he might not be aware of that.

**Comment by hcorson-dosch-usgs** [comment]
@jread-usgs - if you wanted to review the plotted results from the [latest run](https://github.com/USGS-R/lake-temperature-process-models/issues/2#issuecomment-1033243751), they are [here](https://doimspp.sharepoint.com/:f:/r/sites/IIDDStaff/Shared%20Documents/Project%20-%20Modeling%20Lakes/GLM/lake-temperature-process-models/Plots_w_updated_grid_20220210?csf=1&web=1&e=XoNnhB)

**Comment by jordansread** [comment]
@hcorson-dosch I've taken a look at these and they look good to me. But given the small % subset from the total, I don't feel comfortable signing off on these normal looking patterns applying to other lakes. I think it is useful to have these detailed plotting available when we hone in on a problem lake, but seems we'll need an alternative set of diagnostic metrics and/or plots to help us see if the simulations are realistic.

**Comment by hcorson-dosch-usgs** [comment]
Yes, I agree. I'll put it on my list to generate some more diagnostic plots and metrics.

**Comment by lindsayplatt** [comment]
^ I believe we did this in #37. Thinking that we can call this issue closed generate specific ones if there is anything strange to dig into (as we did with #34)
