### ISSUE TITLE
Run GLM models using updated NA cell fix

### ISSUE THREAD

**Issue by lindsayplatt** [DOI-USGS/lake-temperature-process-models#32]
Following https://github.com/USGS-R/lake-temperature-model-prep/issues/296 and https://github.com/USGS-R/lake-temperature-model-prep/pull/309, we will have new driver data for some of the cells that previously had missing data. We will need to incorporate these and the new lake cell xwalk into this repo and re-run the GLM models.

**Comment by hcorson-dosch-usgs** [comment]
Wait until #36 and [hypso code PR](https://github.com/USGS-R/lake-temperature-model-prep/pull/319) are merged in

**Comment by hcorson-dosch-usgs** [comment]
Completed on 4/19/2022
