### ISSUE TITLE
How do we want to combine the GLM output?

### ISSUE THREAD

**Issue by hcorson-dosch-usgs** [DOI-USGS/lake-temperature-process-models#7]
As of now, I'm simply combining the output from each of the three time periods (1980-1999, 2040-2059, and 2080-2099) for each lake for each set of GCM driver data, as outlined in #6, which lands us with 6 output feather files per lake. But I realized that we haven't discussed how we'll want to package it up for delivery to Gretchen. Do we want it broken out by GCM like this, or do we want to ensemble the GCM output for each lake into a single timeseries? Or do we want to retain the predictions associated with each GCM, but bundle them all into a single file for each lake?  Or something else? What did you have in mind @jread-usgs ?

**Comment by hcorson-dosch-usgs** [comment]
@jread-usgs - pinging you again here, since Lindsay and I are starting to think ahead about the data release and how we'll want to package up and share our results with Gretchen & co through the SB item before the data release is finalized.

**Comment by jordansread** [comment]
For now, I'd suggest we punt and plan to use feather files for each lake/GCM combo. In a future discussion, I'd like to propose a new data release format that uses netcdf discrete sampling geom to put all of the lakes in a single file, like we did with Jared's EA-LSTM data release. Do do so, we'd need to address one challenge with depth but there are options for that. The reason I don't think we should pivot to that format now is because I'm not totally clear on how usable it is for our partners.

**Comment by hcorson-dosch-usgs** [comment]
Okay, thanks Jordan. At the moment the output is also in wide format, and the lake id and GCM name are included in the file name, but not as columns. @jread-usgs , @lindsayplatt do you think we should move to long format and/or include the identifying info in columns in addition to in the file name, or is that not worth the increase in file size?
![image](https://user-images.githubusercontent.com/54007288/148419464-a0360782-3b13-4588-becc-dbfe3ebfe4b5.png)

**Comment by jordansread** [comment]
My preference would be to stick with the wide format so we stick to the prior format until we've had a chance to talk about whether a change from that would be worthwhile.

**Comment by lindsayplatt** [comment]
We've also had a previous pattern of using the filenames to distinguish different model outputs (like with GLM vs PGDL outputs), so I don't think it is unusual to continue to do that.

**Comment by hcorson-dosch-usgs** [comment]
Closing this issue since we landed on sticking with the [current approach](https://github.com/USGS-R/lake-temperature-process-models/blob/main/2_run.R#L18-L37) of saving the wide-formatted data in a feather file for each lake/gcm combo (6 feather files per lake), with the lake id and gcm name in the filename.
