### ISSUE TITLE
Need to programmatically pull GLM version

### ISSUE THREAD

**Issue by hcorson-dosch-usgs** [DOI-USGS/lake-temperature-process-models#8]
We'd like to be able to programmatically extract the GLM version and include it in the diagnostic tble we return from our model runs.

the function `GLM3r::glm_version()` returns a message, and the value `0`:
```r
     
    -------------------------------------------------------
    |  General Lake Model (GLM)   Version 3.1.0a4         |
    -------------------------------------------------------
     
     glm built using MSC version 1916
--help  : show this blurb
--nml <nmlfile> : get parameters from nmlfile
--xdisp : display temp/salt and selected others in x-window
--xdisp <plotsfile> : like --xdisp, but use <plotsfile> instead of plots.nml
--saveall : save plots to png files
--save-all-in-one : save all plots to png file
--save-all-in-one <destfile> : save all plots to png file <destfile>
--quiet   : less messages
--quiet <level> : set quiet level (1-10)
[1] 0
```

Jordan did some digging, and realized we could set `stdout=TRUE` to have the output [go to the  assignment value](https://github.com/GLEON/GLM3r/blob/e8eec85872fabb17a1d6a132cae4ff8fc46afafd/R/run_glm.R#L75). That gets us the following:

```r
> out <- system2("C:/Users/hcorson-dosch/Documents/R/AquaticEcoDynamics/GLM/glm", wait = TRUE, stdout = TRUE, stderr = "", args = "--help")
> out
 [1] "     "                                                                       
 [2] "    -------------------------------------------------------"                 
 [3] "    |  General Lake Model (GLM)   Version 3.1.0a4         |"                 
 [4] "    -------------------------------------------------------"                 
 [5] "     "                                                                       
 [6] "     glm built using MSC version 1916"                                       
 [7] "--help  : show this blurb"                                                   
 [8] "--nml <nmlfile> : get parameters from nmlfile"                               
 [9] "--xdisp : display temp/salt and selected others in x-window"                 
[10] "--xdisp <plotsfile> : like --xdisp, but use <plotsfile> instead of plots.nml"
[11] "--saveall : save plots to png files"                                         
[12] "--save-all-in-one : save all plots to png file"                              
[13] "--save-all-in-one <destfile> : save all plots to png file <destfile>"        
[14] "--quiet   : less messages"                                                   
[15] "--quiet <level> : set quiet level (1-10)"                                    
> out[3]
[1] "    |  General Lake Model (GLM)   Version 3.1.0a4         |"
```

That almost gets us there, but there's two issues:
1) we'd need to parse that line with regex (not a big deal)
2) I'm having to manually provide my path to GLM, despite it being set with `Sys.setenv(GLM_PATH = "C:/Users/hcorson-dosch/Documents/R/AquaticEcoDynamics/GLM/glm")`, so we'd either need `system2` to recognize that path or pass the path as an argument to our execution function (more of a pain).

In light of these issues, Jordan is recommending solving this issue at the `GLM3r` package level, by solving [this issue he created](https://github.com/GLEON/GLM3r/issues/23) and putting it in a PR to the package and then updating the package version.

**Comment by jordansread** [comment]
First part of this doesn't require us to make the decision as to where we solve the problem (this repo vs the `GLM3r` pkg itself). We need to figure out how to extract `"3.1.0a4"` from `"    |  General Lake Model (GLM)   Version 3.1.0a4         |"`

After that we'll check back in with GLM3r devs/users to see if this feature would be useful to others and welcomed as an update to the pkg. I think it may be easier to do there because it already handles issues with different OS's and env variables.

**Comment by hcorson-dosch-usgs** [comment]
Oh ok - I can tackle that regex, then, if you like.

**Comment by jordansread** [comment]
Sorry, I was just stating how I'd approach the problem. I'm good with taking it on.

**Comment by jordansread** [comment]
```r
stringr::str_extract(" | General Lake Model (GLM) Version 3.1.0a4 |", '(?<=Version\\ ).+?(?=\\ )')
[1] "3.1.0a4"
```
Seems to do it. That would be a solution for the pipeline since we don't care about the stringr dependency. But that won't work for `GLM3r` pkg since we don't want to add other dependencies without a really good reason. 

```r
strcapture('(?<=Version\\ ).+?(?=\\ )', " | General Lake Model (GLM) Version 3.1.0a4 |", proto = data.frame(version = character(0)), perl = TRUE)
Error in strcapture("(?<=Version\\ ).+?(?=\\ )", " | General Lake Model (GLM) Version 3.1.0a4 |",  : 
  The number of captures in 'pattern' != 'length(proto)'
```
Fails for me but not sure why it is capturing more or less than one thing

**Comment by jordansread** [comment]
In base R:
```r
regmatches(" | General Lake Model (GLM) Version 3.1.0a4 |", regexec("(?<=Version\ ).+?(?=\ )", " | General Lake Model (GLM) Version 3.1.0a4 |", perl = TRUE))[[1]]
[1] "3.1.0a4"
```

**Comment by jordansread** [comment]
@hcorson-dosch this seems to be what we'd want: https://github.com/jread-usgs/GLM3r/commit/830d04ac5b29ca831cbea8ec98026190c331acd8

```r
glm_version()
     
    -------------------------------------------------------
    |  General Lake Model (GLM)   Version 3.2.0a3         |
    -------------------------------------------------------
     
     glm built using gcc version 4.2.1
glm_version(as_char = TRUE)
[1] "3.2.0a3"
```

**Comment by hcorson-dosch-usgs** [comment]
Great! should I go ahead and add this into my PR?

**Comment by jordansread** [comment]
Sure - would you be adding the `glm_version(as_char = TRUE)` to your PR in that `tibble` and suggesting a GH install, or would you add the whole GLM3r change to the PR? I think I'd recommend the former, keeping this in GLM3r, and I can do a PR on that repo and also up the package version so it is clear what needs to be installed (and eventually, what needs to be in the shifter container). But let me know if you were thinking of pulling that whole change and backing code in here.

**Comment by hcorson-dosch-usgs** [comment]
Oh, gosh, I'm sorry. I was referring to adding the regex only, but I was forgetting my own note about the glm path 🤦‍♀️.

I can add either a) add `glm_version(as_char = TRUE)` and suggest a GH install, or b) leave my PR as is, and we can wait to add that to the tibble once the change is PR'd into GLM3r.

**Comment by jordansread** [comment]
I think keeping your PR as-is and leaving this issue open until we resolve it would be good. We'll get a sense if others are interested in this functionality soon

**Comment by jordansread** [comment]
Merged here https://github.com/GLEON/GLM3r/pull/24
